name: Merge Main -> Production

on: workflow_dispatch

jobs:
  merge-main-into-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge main -> production
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GIT_AUTHOR_NAME: devOpsBot
          # GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          # GIT_COMMITTER_NAME: devOpsBot
          # GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
        run: |
          git fetch origin production
          git checkout production
          git merge origin/main --ff-only
          git push origin production

# 1)
# env:
#   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# run: |
#   git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/<github_user_name>/<repo_name>
#   git config user.name "DevOpsBot"
#   git config user.email "test@test.com"
#   git fetch origin main
#   git checkout -b main origin/main
#   git merge origin/production --ff-only
#   git push origin main

# 2)
# - name: Create a release candidate branch with the next version number
# env:
#   GITHUB_TOKEN: ${{ secrets.DEV_OPS_BOT_TOKEN }}
#   GIT_AUTHOR_NAME: devOpsBot
#   GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
#   GIT_COMMITTER_NAME: devOpsBot
#   GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
# run: |
#   git checkout -b release/${{steps.get_next_version.outputs.next_version}}
#   git push origin release/${{steps.get_next_version.outputs.next_version}}

# jobs:
#   fast_forward_job:
#     name: Fast Forward
#     if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/ff')
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code into workspace directory
#         uses: actions/checkout@v2
#         with:
#           fetch-depth: 0

#       - name: Fast Forward PR
#         id: ff-action
#         uses: endre-spotlab/fast-forward-js-action@master
#         with:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           success_message: 'Success! Fast forwarded ***source_head*** to ***target_base***! ```git checkout target_base && git merge source_head --ff-only``` '
#           failure_message: 'Failed! Cannot do fast forward!'
#           staging_branch: 'main'
#           production_branch: 'production'

